version: '3'
services:
  wahelp:
    build: ./
    volumes:
      - ./bootstrap:/src/bootstrap
      - ./core:/src/core
      - ./src:/src/src
      - ./public:/src/public
      - ./sql:/src/sql
    ports:
      - 8082:80
    environment:
      DB_HOST: pgsql
      DB_PORT: 5432
      DB_DATABASE: wahelp_db
      DB_USERNAME: admin
      DB_PASSWORD: admin
    depends_on:
      - pgsql

  pgsql:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wahelp_db
    ports:
      - 6000:5432
    volumes:
      - pgsql_data:/var/lib/postgresql/data

volumes:
  pgsql_data:
